import assert from 'node:assert/strict'
import { test } from 'node:test'
import { checkBash, checkEdit } from './guard.mjs'

test('checkBash blocks --no-verify on commit and push', () => {
  assert.match(checkBash('git commit --no-verify -m "x"', 'feature'), /--no-verify/)
  assert.match(checkBash('git push --no-verify', 'feature'), /--no-verify/)
})

test('checkBash blocks pushing to main or master by refspec', () => {
  for (const command of ['git push origin main', 'git push -u origin master', 'git push origin HEAD:main', 'git push --force origin main']) {
    assert.match(checkBash(command, 'feature'), /main/, command)
  }
})

test('checkBash sees through git -C and -c options', () => {
  assert.match(checkBash('git -C ~/repo push origin main', 'feature'), /main/)
  assert.match(checkBash('git -c core.x=y push origin main', 'feature'), /main/)
})

test('checkBash blocks a bare push while on main', () => {
  assert.match(checkBash('git push', 'main'), /main/)
  assert.match(checkBash('cd repo && git push -q', 'main'), /main/)
})

test('checkBash allows pushing a feature branch, including from main by refspec', () => {
  assert.equal(checkBash('git push -qu origin init-repo', 'init-repo'), null)
  assert.equal(checkBash('git push', 'feature'), null)
  assert.equal(checkBash('git push origin maintenance-fix', 'main'), null)
})

test('checkBash blocks AI attribution in commit messages and PR bodies', () => {
  const trailer = 'git commit -m "add page" -m "Co-Authored-By: Claude <noreply@anthropic.com>"'
  assert.match(checkBash(trailer, 'feature'), /attribution/)
  assert.match(checkBash('gh pr create --body "🤖 Generated with [Claude Code](https://claude.com)"', 'feature'), /attribution/)
})

test('checkBash ignores attribution text outside commits and PRs, and ordinary commands', () => {
  assert.equal(checkBash('grep -rn "Co-Authored-By: Claude" .', 'main'), null)
  assert.equal(checkBash('pnpm check', 'main'), null)
})

test('checkEdit blocks lockfiles and files marked generated', () => {
  assert.match(checkEdit('/repo/pnpm-lock.yaml', ''), /generated/)
  assert.match(checkEdit('/repo/src/client.ts', '// @generated by openapi\nexport {}'), /generated/)
  assert.match(checkEdit('/repo/schema.go', '// Code generated. DO NOT EDIT.\n'), /generated/)
})

test('checkEdit allows ordinary files, including ones mentioning generation later on', () => {
  assert.equal(checkEdit('/repo/src/a.ts', 'export const a = 1\n'.repeat(10) + '// @generated sample'), null)
  assert.equal(checkEdit('/repo/new.ts', null), null)
})
